package com.samsung.android.gallery.database.dbtype;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public enum ExtrasID {
    TOTAL_SMART_CROP_RATIO,
    TOTAL_SMART_CROP_DEVICE_RATIO,
    ORIGIN_PATH,
    ORIGINAL_URI,
    ORIGINAL_FILE_ID,
    HOVER_DATA_POSITION,
    FACE_GROUP_ID,
    CLUSTER_TYPE,
    CREATURE_FACE_GROUP_IDS,
    PDC_TIME_INFO,
    REMASTERING_STATE,
    SELECTED_FILTER,
    CREATURE_RECOMMENDED_IDS,
    MY_QUERY_MAIN_CATEGORY,
    MY_QUERY_TERM,
    MY_QUERY_PEOPLE_ONLY_THEM,
    SPACE_COVER_RECT_RATIO,
    SCREENSHOT_FILTER_ON,
    RECAP_DATA,
    EOE
}
