package com.samsung.android.gallery.app.ui.list.stories.category.abstraction;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public enum InternalEvent {
    EVENT_FAVORITE,
    UPDATE_BADGE,
    SHOW_SLIDESHOW,
    REQUEST_PREVIEW,
    HIDDEN_CHANGE,
    REDUCED_TRANSPARENCY_CHANGED,
    UPDATE_EXTRA_PADDING,
    ON_DEMAND_STORY_SAVED,
    SELECT_MODE_CHANGE,
    SELECT_ITEM,
    SELECTED_ITEMS,
    SELECT_ALL,
    SET_CURRENT_ITEM,
    HEADER_SIZE_CHANGED,
    ON_HEADER_ATTACHED,
    TRANSITORY_PAGE_SELECTED,
    TRANSITORY_TRANSFORM_PAGE,
    ON_DATA_SIZE_CHANGED,
    ON_DATE_TIME_CHANGED
}
