package com.videolibrary.data.service

import android.content.Context
import android.net.Uri
import com.videolibrary.data.cache.VideoThumbnailCache
import com.videolibrary.data.util.FileLogger as Log
import kotlinx.coroutines.*
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

/**
 * Background thumbnail generation service.
 *
 * **Samsung Gallery pattern:**
 * - Generates thumbnails in background without blocking UI
 * - Processes queue with limited concurrency (3 parallel extractions)
 * - Silent operation (no UI feedback)
 * - Cancellable when user navigates away
 *
 * **Usage:**
 * ```kotlin
 * val service = ThumbnailGenerationService(context)
 * service.preloadThumbnails(videos) // Non-blocking
 * ```
 */
class ThumbnailGenerationService(private val context: Context) {

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val isRunning = AtomicBoolean(false)
    private var currentJob: Job? = null

    companion object {
        /** Maximum concurrent thumbnail extractions (Samsung uses 3-5) */
        private const val MAX_CONCURRENCY = 3

        @Volatile
        private var instance: ThumbnailGenerationService? = null

        fun getInstance(context: Context): ThumbnailGenerationService {
            return instance ?: synchronized(this) {
                instance ?: ThumbnailGenerationService(context.applicationContext).also {
                    instance = it
                }
            }
        }
    }

    /**
     * Preloads thumbnails for a list of video URIs in the background.
     *
     * **Strategy:**
     * - Cancels any previous preload job
     * - Filters out videos that already have cached thumbnails
     * - Processes remaining videos with limited concurrency
     * - Non-blocking (returns immediately)
     *
     * @param videoUris List of (URI, dateModified) pairs to preload
     */
    fun preloadThumbnails(videoUris: List<Pair<Uri, Long>>) {
        // Cancel previous job if running
        currentJob?.cancel()

        if (videoUris.isEmpty()) {
            return
        }

        currentJob = scope.launch {
            isRunning.set(true)
            val processed = AtomicInteger(0)
            val total = videoUris.size

            try {
                val cache = try {
                    VideoThumbnailCache.getInstance()
                } catch (e: IllegalStateException) {
                    Log.w("ThumbnailGenerationService", "Cache not initialized, skipping preload")
                    return@launch
                }

                // Filter out videos that already have cached thumbnails
                val uncachedVideos = videoUris.filter { (uri, dateModified) ->
                    !cache.exists(uri, dateModified)
                }

                if (uncachedVideos.isEmpty()) {
                    Log.i("ThumbnailGenerationService", "All $total thumbnails already cached")
                    return@launch
                }

                Log.i("ThumbnailGenerationService",
                    "Starting preload: ${uncachedVideos.size}/$total need generation"
                )

                // Process queue with limited concurrency (Samsung's pattern)
                uncachedVideos.chunked(MAX_CONCURRENCY).forEach { batch ->
                    if (!isActive) return@launch // Cancelled

                    // Process batch in parallel
                    batch.map { (uri, dateModified) ->
                        async {
                            try {
                                // Check cache again (may have been generated by UI)
                                if (cache.exists(uri, dateModified)) {
                                    return@async
                                }

                                // Extract thumbnail (this is the slow part - 1-3 seconds)
                                val thumbnail = extractThumbnailForService(context, uri)

                                // Save to cache
                                if (thumbnail != null) {
                                    cache.put(uri, dateModified, thumbnail)
                                    val count = processed.incrementAndGet()

                                    // Log progress every 10 thumbnails
                                    if (count % 10 == 0) {
                                        Log.i("ThumbnailGenerationService",
                                            "Progress: $count/${uncachedVideos.size} generated"
                                        )
                                    }
                                }
                            } catch (e: Exception) {
                                Log.w("ThumbnailGenerationService", "Failed to generate thumbnail: ${e.message}")
                            }
                        }
                    }.awaitAll()
                }

                Log.i("ThumbnailGenerationService",
                    "Preload complete: ${processed.get()}/${uncachedVideos.size} generated successfully"
                )

            } finally {
                isRunning.set(false)
            }
        }
    }

    /**
     * Cancels any ongoing thumbnail generation.
     */
    fun cancel() {
        currentJob?.cancel()
        isRunning.set(false)
    }

    /**
     * Checks if the service is currently generating thumbnails.
     */
    fun isGenerating(): Boolean = isRunning.get()

    /**
     * Extracts a thumbnail using the same brightness-aware algorithm.
     * (Copied from VideoThumbnail.kt to avoid UI dependencies)
     */
    private fun extractThumbnailForService(context: Context, uri: Uri): android.graphics.Bitmap? {
        val retriever = android.media.MediaMetadataRetriever()
        var bestFrame: android.graphics.Bitmap? = null
        var bestBrightness = 0f

        try {
            retriever.setDataSource(context, uri)

            val durationMs = retriever.extractMetadata(
                android.media.MediaMetadataRetriever.METADATA_KEY_DURATION
            )?.toLongOrNull() ?: return null

            // Seek through video looking for brightest frame
            for (sec in 1..10) { // MAX_SEEK_SEC = 10
                val timeUs = sec * 1_000_000L
                if (timeUs > durationMs * 1_000L) break

                val frame = retriever.getFrameAtTime(
                    timeUs, android.media.MediaMetadataRetriever.OPTION_CLOSEST_SYNC
                ) ?: continue

                val brightness = calculateBrightness(frame)

                if (brightness > bestBrightness) {
                    bestFrame?.recycle()
                    bestFrame = frame
                    bestBrightness = brightness
                } else {
                    frame.recycle()
                }

                if (bestBrightness >= 28f) break // BRIGHTNESS_THRESHOLD = 28f
            }
        } catch (_: Exception) {
            // return whatever we have
        } finally {
            try {
                retriever.close()
            } catch (_: Exception) {
                try { @Suppress("DEPRECATION") retriever.release() } catch (_: Exception) {}
            }
        }

        return bestFrame
    }

    /**
     * Calculates average brightness of a bitmap (ITU-R BT.601 luminance).
     * Samples 8×8 grid for speed.
     */
    private fun calculateBrightness(bitmap: android.graphics.Bitmap): Float {
        val w = bitmap.width
        val h = bitmap.height
        if (w == 0 || h == 0) return 0f

        val stepX = (w / 8).coerceAtLeast(1)
        val stepY = (h / 8).coerceAtLeast(1)
        var sum = 0f
        var count = 0

        var y = 0
        while (y < h) {
            var x = 0
            while (x < w) {
                val pixel = bitmap.getPixel(x, y)
                val r = (pixel shr 16) and 0xFF
                val g = (pixel shr 8) and 0xFF
                val b = pixel and 0xFF
                sum += 0.299f * r + 0.587f * g + 0.114f * b
                count++
                x += stepX
            }
            y += stepY
        }

        return if (count > 0) sum / count else 0f
    }
}

