package com.videolibrary.data.service

import android.content.Context
import android.net.Uri
import com.videolibrary.data.cache.VideoThumbnailCache
import com.videolibrary.data.util.VideoThumbnailExtractor
import com.videolibrary.data.util.FileLogger as Log
import kotlinx.coroutines.*
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Background thumbnail generation service.
 *
 * **Samsung Gallery pattern:**
 * - Generates thumbnails in background without blocking UI
 * - Processes queue with limited concurrency (3 parallel extractions)
 * - Silent operation (no UI feedback)
 * - Cancellable when user navigates away
 *
 * **Usage:**
 * ```kotlin
 * val service = ThumbnailGenerationService(context)
 * service.preloadThumbnails(videos) // Non-blocking
 * ```
 */
class ThumbnailGenerationService(private val context: Context) {

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val isRunning = AtomicBoolean(false)
    private var currentJob: Job? = null

    companion object {
        /** Maximum concurrent thumbnail extractions (Samsung uses 3-5) */
        private const val MAX_CONCURRENCY = 3

        @Volatile
        private var instance: ThumbnailGenerationService? = null

        fun getInstance(context: Context): ThumbnailGenerationService {
            return instance ?: synchronized(this) {
                instance ?: ThumbnailGenerationService(context.applicationContext).also {
                    instance = it
                }
            }
        }
    }

    /**
     * Preloads thumbnails for a list of video URIs in the background.
     *
     * **Strategy:**
     * - Cancels any previous preload job
     * - Filters out videos that already have cached thumbnails
     * - Processes remaining videos with limited concurrency
     * - Non-blocking (returns immediately)
     *
     * @param videoUris List of (URI, dateModified) pairs to preload
     */
    fun preloadThumbnails(videoUris: List<Pair<Uri, Long>>) {
        // Cancel previous job if running
        currentJob?.cancel()

        if (videoUris.isEmpty()) {
            return
        }

        currentJob = scope.launch {
            isRunning.set(true)

            try {
                val cache = try {
                    VideoThumbnailCache.getInstance()
                } catch (e: IllegalStateException) {
                    return@launch
                }

                // Filter out videos that already have cached thumbnails
                val uncachedVideos = videoUris.filter { (uri, dateModified) ->
                    !cache.exists(uri, dateModified)
                }

                if (uncachedVideos.isEmpty()) {
                    return@launch
                }

                // Process queue with limited concurrency (Samsung's pattern)
                uncachedVideos.chunked(MAX_CONCURRENCY).forEach { batch ->
                    if (!isActive) return@launch // Cancelled

                    // Process batch in parallel
                    batch.map { (uri, dateModified) ->
                        async {
                            try {
                                // Check cache again (may have been generated by UI)
                                if (cache.exists(uri, dateModified)) {
                                    return@async
                                }

                                // Extract thumbnail (this is the slow part - 1-3 seconds)
                                val thumbnail = extractThumbnailForService(context, uri)

                                // Save to cache
                                if (thumbnail != null) {
                                    cache.put(uri, dateModified, thumbnail)
                                }
                            } catch (e: Exception) {
                                Log.w("ThumbnailGenerationService", "Failed to generate thumbnail: ${e.message}")
                            }
                        }
                    }.awaitAll()
                }

            } finally {
                isRunning.set(false)
            }
        }
    }

    /**
     * Cancels any ongoing thumbnail generation.
     */
    fun cancel() {
        currentJob?.cancel()
        isRunning.set(false)
    }

    /**
     * Checks if the service is currently generating thumbnails.
     */
    fun isGenerating(): Boolean = isRunning.get()

    /**
     * Extracts a thumbnail using the same Samsung-style embedded art / frame sampler.
     */
    private fun extractThumbnailForService(context: Context, uri: Uri): android.graphics.Bitmap? {
        return VideoThumbnailExtractor.extract(context, uri)
    }
}
