package com.samsung.android.gallery.module.remotegallery;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public abstract class HtmlGallery {
    public static String BODY = " <body>\n\n<script type=\"text/javascript\">\n\nfunction getQueryVariable(variable) {\n  var query = window.location.search.substring(1);\n  var vars = query.split(\"&\");\n  for (var i=0;i<vars.length;i++) {\n    var pair = vars[i].split(\"=\");\n    if (pair[0] == variable) {\n      return pair[1];\n    }\n  } \n return 0;}var pageNum=__PAGE_NUM__;var stop=false;$(\"body\").swiperight(function() {\nif(stop){return;}else{stop=true;}setTimeout(function(){stop=false;},1000);       if(pageNum<1)return;pageNum--;console.log('swiperight to '+pageNum);    $.mobile.changePage(\"/?page=\"+pageNum,{transition:'pop',reloadPage:false,type:'GET',reverse:true});\n});$(\"body\").swipeleft(function() {\nif(stop){return;}else{stop=true;}setTimeout(function(){stop=false;},1000);       pageNum++;console.log('swipeleft to '+pageNum);    $.mobile.changePage(\"/?page=\"+pageNum,{transition:'pop',reloadPage:false,type:'GET',reverse:false});\n});console.log('test='+pageNum+\"/\"+$(\"body\"));</script>    <div class=\"container\" id=\"mainC\">\n      <a href='__DEEPLINK__'><h2 class=\"heading-text\">Launch <span>Gallery</span></h2><h3></h3><h4 style='text-align:center;'>Swipe to Paging. #__PAGE_NUM__</h4></a>\n      <div class=\"image-gallery\">\n        <div class=\"column\">\n        __COLUMN1__\n        </div>\n        <div class=\"column\">\n        __COLUMN2__\n        </div>\n      </div>\n    </div>\n  </body>";
    public static String CSS = "* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\n\nbody {\n  font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\n}\na { color: inherit;   text-decoration:none;} \n.container {\n  padding: 40px 5%;\n}\n\n.heading-text {\n  margin-bottom: 2rem;\n  font-size: 2rem;\n}\n\n.rotation-wrapper-outer {\n  display: table;\n}\n.rotation-wrapper-inner {\n  padding: 50% 0;\n  height: 0;\n}\n.heading-text span {\n  font-weight: 100;\n}\n\n/* Responsive image gallery rules begin*/\n\n.image-gallery {\n  /* Mobile first */\n  display: flex;\n  flex-direction: row;\n  gap: 10px;\n}\n\n.image-gallery .column {\n  display: flex;\n  flex-direction: column;\n  gap: 10px;\n}\n\n.image-item img {\n\n  width: 100%;\n  border-radius: 5px;\n  height: 100%;\n  display: block;\n  object-fit: cover;\n}\n\n/* overlay styles */\n\n.image-item {\n  position: relative;\n  cursor: pointer;\n}\n\n.overlay {\n  position: absolute;\n  width: 100%;\n  height: 100%;\n  background: rgba(57, 57, 57, 0.502);\n  top: 0;\n  left: 0;\n  transform: scale(0);\n  transition: all 0.2s 0.1s ease-in-out;\n  color: #fff;\n  /* center overlay content */\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n\n/* hover */\n.image-item:hover .overlay {\n  transform: scale(1);\n}";
    public static String HEADER = "  <head>\n\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n    <title>Remote Gallery</title>\n    <link rel=\"stylesheet\" href=\"style.css\" />\n\n<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\" />\n<script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\n<script src=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script>  </head>";
    public static String ITEM = "          <div class=\"image-item\">\n          \n <img src=\"__SRC__\" alt=\"\" __STYLE__/>\n            <div class=\"overlay\"><span>__TITLE__</span></div>\n          </div>\n";
}
