package o;

import android.graphics.RuntimeShader;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public abstract /* synthetic */ class c {
    public static /* synthetic */ RuntimeShader c() {
        return new RuntimeShader("uniform float2 resolution;uniform vec4 color;uniform float startAlpha;uniform vec4 easing;float cubicBezier(float t, float x1, float y1, float x2, float y2) {    if (t <= 0.0) return 0.0;    if (t >= 1.0) return 1.0;    float s = t;    float u2, s2, s3;    for (int i = 0; i < 6; i++) {        float u = 1.0 - s;        u2 = u * u;        s2 = s * s;        float x_current = 3.0 * u2 * s * x1 + 3.0 * u * s2 * x2 + s2 * s;        float dx_ds = 3.0 * u2 * x1 + 6.0 * u * s * (x2 - x1) + 3.0 * s2 * (1.0 - x2);        if (abs(dx_ds) < 0.0001) break;        s = s - (x_current - t) / dx_ds;        s = clamp(s, 0.0, 1.0);        if (abs(x_current - t) < 0.0001) break;    }    float u = 1.0 - s;    u2 = u * u;    s2 = s * s;    s3 = s2 * s;    return 3.0 * u2 * s * y1 + 3.0 * u * s2 * y2 + s3;}vec4 main(vec2 fragCoord) {    float t = clamp(fragCoord.y / resolution.y, 0.0, 1.0);    t = clamp(t * (1.0 - startAlpha) + startAlpha, 0.0, 1.0);    float eased;    eased = 1.0 - cubicBezier(t, easing.x, easing.y, easing.z, easing.w);    return vec4(color.rgb * eased, eased);}");
    }

    public static /* synthetic */ RuntimeShader d(String str) {
        return new RuntimeShader(str);
    }

    /*  JADX ERROR: IndexOutOfBoundsException in pass: MethodInlineVisitor
        java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        	at java.util.ArrayList.get(ArrayList.java:435)
        	at jadx.core.dex.visitors.MethodInlineVisitor.inlineMth(MethodInlineVisitor.java:57)
        	at jadx.core.dex.visitors.MethodInlineVisitor.visit(MethodInlineVisitor.java:47)
        */
    public static /* synthetic */ void f() {
        /*
            android.graphics.RuntimeShader r0 = new android.graphics.RuntimeShader
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: o.c.f():void");
    }

    public static /* synthetic */ RuntimeShader t() {
        return new RuntimeShader("    uniform shader uContent;\n    uniform vec2 uCenter;\n    uniform vec2 uSize;\n    uniform vec4 uCornerR; // cornerR : tl, tr, br, bl order for x, y, z, w vec4\n    uniform int uRoundingMode;\n\n    float sdRoundedRect(vec2 p) {\n        vec2 halfSize = uSize * 0.5;\n        vec2 local = abs(p - uCenter) - halfSize + vec2(uCornerR.x);\n        return length(max(local, 0.0)) - uCornerR.x;\n    }\n\n    float sdRoundedRectPC(vec2 p) {\n        vec2 h = uSize * 0.5; //half\n        vec2 d = p - uCenter; //distance\n        vec2 ad = abs(d); //abs-distance\n        float r = (d.x > 0.0) ? ((d.y > 0.0) ? uCornerR.w : uCornerR.y) : // bot-right, top-right\n             ((d.y > 0.0) ? uCornerR.z : uCornerR.x); // bot-left, top-left order\n        vec2 local = ad - (h - vec2(r)); //same with sdRoundedRect\n        return length(max(local, 0.0)) + min(max(local.x, local.y), 0.0) - r;\n    }\n\n    half4 main(float2 coord) {\n         // return : masked area  RGBA\n         if (uRoundingMode <= 0) { // NONE or ALL\n            if (sdRoundedRect(coord) <= 0.0) {\n                return half4(1.0,0.0,0.0,1.0);\n            }\n        } else if (uRoundingMode == 1) {\n            if (sdRoundedRectPC(coord) <= 0.0) {\n                return half4(1.0,0.0,0.0,1.0);\n            }\n        } else if (uRoundingMode == 2) {\n            if (sdRoundedRectPC(coord) <= 0.0) {\n                return half4(1.0,0.0,0.0,1.0);\n            }\n        }\n        return half4(0.0,0.0,0.0,0.0);\n    }\n");
    }

    public static /* synthetic */ RuntimeShader x() {
        return new RuntimeShader("    uniform shader uContent;\n    uniform vec2 uCenter;\n    uniform vec2 uSize;\n    uniform vec4 uCornerR; // cornerR : tl, tr, br, bl order for x, y, z, w vec4\n    uniform int uRoundingMode;\n\n    float sdRoundedRect(vec2 p) {\n        vec2 halfSize = uSize * 0.5;\n        vec2 local = abs(p - uCenter) - halfSize + vec2(uCornerR.x);\n        return length(max(local, 0.0)) - uCornerR.x;\n    }\n\n    float sdRoundedRectPC(vec2 p) {\n        vec2 h = uSize * 0.5; //half\n        vec2 d = p - uCenter; //distance\n        vec2 ad = abs(d); //abs-distance\n        float r = (d.x > 0.0) ? ((d.y > 0.0) ? uCornerR.w : uCornerR.y) : // bot-right, top-right\n             ((d.y > 0.0) ? uCornerR.z : uCornerR.x); // bot-left, top-left order\n        vec2 local = ad - (h - vec2(r)); //same with sdRoundedRect\n        return length(max(local, 0.0)) + min(max(local.x, local.y), 0.0) - r;\n    }\n\n    half4 main(float2 coord) {\n        if (uRoundingMode <= 0) { // NONE or ALL\n            if (sdRoundedRect(coord) <= 0.0) {\n                return uContent.eval(coord);\n            }\n        } else if (uRoundingMode == 1) {\n            if (sdRoundedRectPC(coord) <= 0.0) {\n                return uContent.eval(coord);\n            }\n        } else if (uRoundingMode == 2) {\n            if (sdRoundedRectPC(coord) <= 0.0) {\n                return uContent.eval(coord);\n            }\n        }\n        return half4(0.0, 0.0, 0.0, 0.0);\n    }\n");
    }

    public static /* synthetic */ RuntimeShader z() {
        return new RuntimeShader("uniform shader uContent;\nuniform half2 uDirection;\nuniform half uBlurRadius;\nuniform vec2 uCenter;\nuniform vec2 uSize;\nuniform vec4 uCornerR; // cornerR : tl, tr, br, bl order for x, y, z, w vec4\nuniform int uRoundingMode;\n\nconst half weight_origin = 0.11; // Weight for origin : 0.22 / 2\nconst half weight_1 = 0.21; //skia does not support const half array\nconst half weight_2 = 0.19;\nconst half weight_3 = 0.16;\nconst half weight_4 = 0.13;\nconst half weight_5 = 0.1;\nconst half weight_6 = 0.07;\nconst half weight_7 = 0.047;\nconst half total_weight = 1.924;\n\nfloat sdRoundedRect(vec2 p) {\n    vec2 halfSize = uSize * 0.5;\n    vec2 local = abs(p - uCenter) - halfSize + vec2(uCornerR.x);\n    return length(max(local, 0.0)) - uCornerR.x;\n}\n\nfloat sdRoundedRectPC(vec2 p) {\n    vec2 h = uSize * 0.5; //half\n    vec2 d = p - uCenter; //distance\n    vec2 ad = abs(d); //abs-distance\n    float r = (d.x > 0.0) ? ((d.y > 0.0) ? uCornerR.w : uCornerR.y) : // bot-right, top-right\n         ((d.y > 0.0) ? uCornerR.z : uCornerR.x); // bot-left, top-left order\n    vec2 local = ad - (h - vec2(r)); //same with sdRoundedRect\n    return length(max(local, 0.0)) + min(max(local.x, local.y), 0.0) - r;\n}\n\nhalf4 main(float2 coord) {\n    if (uRoundingMode <= 0) { // NONE or ALL\n        if (sdRoundedRect(coord) > 0.0) {\n            return uContent.eval(coord);\n        }\n    } else if (uRoundingMode == 1) {\n        if (sdRoundedRectPC(coord) > 0.0) {\n            return uContent.eval(coord);\n        }\n    } else if (uRoundingMode == 2) {\n        if (sdRoundedRectPC(coord) > 0.0) {\n            return uContent.eval(coord);\n        }\n    }\n    half4 color = half4(0);\n\n    half2 off1 = 1 * uBlurRadius * uDirection;\n    half2 off2 = 2 * uBlurRadius * uDirection;\n    half2 off3 = 3 * uBlurRadius * uDirection;\n    half2 off4 = 4 * uBlurRadius * uDirection;\n    half2 off5 = 5 * uBlurRadius * uDirection;\n    half2 off6 = 6 * uBlurRadius * uDirection;\n    half2 off7 = 7 * uBlurRadius * uDirection;\n\n    color += uContent.eval(coord) * weight_origin;\n    color += uContent.eval(coord + (off1)) * weight_1;\n    color += uContent.eval(coord - (off1)) * weight_1;\n    color += uContent.eval(coord + (off2)) * weight_2;\n    color += uContent.eval(coord - (off2)) * weight_2;\n    color += uContent.eval(coord + (off3)) * weight_3;\n    color += uContent.eval(coord - (off3)) * weight_3;\n    color += uContent.eval(coord + (off4)) * weight_4;\n    color += uContent.eval(coord - (off4)) * weight_4;\n    color += uContent.eval(coord + (off5)) * weight_5;\n    color += uContent.eval(coord - (off5)) * weight_5;\n    color += uContent.eval(coord + (off6)) * weight_6;\n    color += uContent.eval(coord - (off6)) * weight_6;\n    color += uContent.eval(coord + (off7)) * weight_7;\n    color += uContent.eval(coord - (off7)) * weight_7;\n\n    return color / total_weight;\n}\n");
    }
}
