package com.samsung.android.gallery.module.trash.abstraction;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public enum TrashLogType {
    DELETE_SINGLE,
    DELETE_MULTIPLE,
    DELETE_BY_PROVIDER,
    DELETE_MULTIPLE_REQUEST,
    EMPTY_SINGLE,
    EMPTY_MULTIPLE,
    EMPTY_EXPIRED,
    EMPTY_ABNORMAL,
    EMPTY_BY_MYFILES,
    MOVE_TO_TRASH_SINGLE,
    MOVE_TO_TRASH_MULTIPLE,
    MOVE_TO_BY_PROVIDER,
    RESTORE_SINGLE,
    RESTORE_MULTIPLE,
    TRASH_UPDATE,
    TRASH_ENABLE,
    TRASH_MP_RECOVER,
    TRASH_ABNORMAL_RECOVER
}
