package com.samsung.android.gallery.app.controller.sharing.request;

/* compiled from: r8-map-id-85efad48717c48307252110572a40cba967e8b6d39747b0efe99f107082547d8 */
public enum RequestCmdType {
    REQUEST_SYNC,
    REQUEST_LEAVE_GROUP,
    REQUEST_DELETE_GROUP,
    REQUEST_DELETE_SPACE,
    REQUEST_CREATE_FAMILY_SPACE,
    REQUEST_DELETE_FAMILY_SPACE,
    REQUEST_UPDATE_SPACE,
    REQUEST_ADD_CONTENTS,
    REQUEST_DELETE_CONTENTS,
    REQUEST_DOWNLOAD_CONTENTS,
    REQUEST_STREAMING_VIDEO,
    REQUEST_INVITATION_SYNC,
    REQUEST_INVITATION_ACCEPTANCE,
    REQUEST_INVITATION_REJECTION,
    REQUEST_CHANGE_SPACE_COVER,
    REQUEST_DOWNLOAD_FOR_PLAY_IN_SHARING,
    REQUEST_DOWNLOAD_COVER,
    REQUEST_MY_QUOTA,
    REQUEST_FAMILY_QUOTA,
    REQUEST_DOWNLOAD_CONTENTS_FOR_SHARING_EDIT,
    REQUEST_MOVE_TO_TRASH,
    REQUEST_RESTORE_FROM_TRASH,
    REQUEST_DELETE_FROM_TRASH,
    REQUEST_EMPTY_FROM_TRASH,
    REQUEST_CREATE_STORY,
    REQUEST_SORT_SHARINGS
}
